[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
   { name = "Akshada Pradhan", email = "asameerpradhan@flatironinstitute.org"},
]
name = "wbpj"
version = "0.0.1"
dependencies = [
    "numpy",
    "finufft >= 2"
    
]
